menubar: false
statusbar: false
language: ru
toolbar:
  - bold italic underline strikethrough blockquote | numlist bullist | link unlink | codesample
plugins:
  - codesample lists link
extended_valid_elements:
  - blockquote[class=blockquote]
  - a[href|target|rel=nofollow]
default_link_target: "_blank"
link_title: false
target_list: false
formats:
  strikethrough:
    - {inline: 'del'}
  underline:
    - {inline: 'u'}
codesample_languages:
  - {text: 'Ruby', value: 'ruby'}
  - {text: 'HTML/XML', value: 'markup'}
  - {text: 'HAML', value: 'haml'}
  - {text: 'JavaScript', value: 'javascript'}
  - {text: 'CSS', value: 'css'}
  - {text: 'PHP', value: 'php'}
  - {text: 'Python', value: 'python'}
  - {text: 'Java', value: 'java'}
  - {text: 'C', value: 'c'}
  - {text: 'C#', value: 'csharp'}
  - {text: 'C++', value: 'cpp'}
